# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseChattingApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  # Pods for FirebaseChattingApp

  target 'FirebaseChattingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FirebaseChattingAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
